### PR TITLE
Added simple bitmap rectangle drawing methods for more common operations

### PR DESCRIPTION
**Pull request by mikeoliphant**
## Description
This PR adds simple rectangle drawing methods for more common operations

## Motivation and Context
Currently the Bitmap class provides only one DrawRectangle method that has a lot of parameter. This PR adds a number of simpler methods that correspond to more common use cases.

## How Has This Been Tested?
Tested locally on M5Core2.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by mikeoliphant** [comment]
Corresponding native PR is here:

https://github.com/nanoframework/nf-interpreter/pull/2399

**Review by josesimoes — CHANGES_REQUESTED** [review]
Welcome improvement! Thanks. 👍🏻 🥇 
Just please address the code smell from Sonarcloud and we're good to merge.

(fixing this will cause a difference checksum for the assembly, please update the native PR accordingly)

**Comment by josesimoes** [comment]
> The "code smell" check wants the DrawRectangle() calls together. I can certainly do that, but I thought it made more sense to have the existing 15-argument method last. The other methods are really DrawRectangle() overloads, even though they have slightly different names for clarity.
> 

We have this name grouping everywhere else (and it's .NET thing) so let's keep following the pattern.

**Review by josesimoes — APPROVED** [review]
LGTM! Thanks for another great improvement. 👍🏻

**Pull request merged**
